### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by alinezhad2018** [SimpleSSD/SimpleSSD#2]
please put a manual to explain how should we run this simulator
and explain a little about the main files of project
regards

**Comment by alinezhad2018** [comment]
Hi
I couldn't find where should I determine the workload in standalone
simulator.

And in which file is the output generate?

**Comment by kukdh1** [comment]
Hi,

For SimpleSSD-Standalone version, you can just follow instructions in [homepage](https://simplessd.org/standalone.html).
You can found trace file format in [here](https://github.com/SimpleSSD/SimpleSSD-Standalone/issues/1).

Thanks.

**Comment by alinezhad2018** [comment]
Tnx for your reply. How can I report the number of p/e cycles of each block of ssd in the output file?

**Comment by kukdh1** [comment]
Hi,

For Standalone (v1.0), `ftl_block.hh` has `int erase_count` variable (See [here](https://github.com/SimpleSSD/SimpleSSD/blob/d74fe803fc0c33f1682aca4b54ed1f0813c0e9b9/ftl_block.hh#L26)).
But standalone will printout all package/die/block statistics when simulation finished.
In the block statistics, you can find erase count.

For FullSystem (v2.0), `ftl/common/block.hh` has `uint32_t eraseCount` variable (See [here](https://github.com/SimpleSSD/SimpleSSD/blob/aff548c5515bed1c60614d43ccc4ee346ade9e84/ftl/common/block.hh#L43))
You should write some codes to printout erase count on fullsystem, because v2.0 does not supports stat printout.

Thanks.
