### ISSUE TITLE
pal.program.bytes is confused when enable MultiPlaneOperation

### ISSUE THREAD

**Issue by CkTD** [SimpleSSD/SimpleSSD#8]
Hi,

I use Simplessd-Standalone to replay a workload from blktrace, at the end of simulation, it gives me statistics, there are
- write.bytes(Write data size in byte), and
- pal.program.bytes(Total program operation bytes)

With default config for simplessd, I get:
- write.bytes 69591040.000000
- pal.program.bytes 36519936.000000

This confused me, the bytes write to NAND is only half of the bytes write to device.

However, with same trace file, after disable MultiPlaneOperation, I get:
- write.bytes 69591040.000000
- pal.program.bytes 71008256.000000

Which sames to be reasonable. Is that something wrong with statistics or I misunderstand something?

Thanks!

**Comment by kukdh1** [comment]
Hi,

It looks like the statistic value reported is wrong. (If you have two planes, you need to multiply 2 to `pal.{read,program,erase}.bytes`)

As PAL does not support multi-plane operation, I mimic the performance of multi-plane OP by making the number of planes (inside of NAND flash) as 1, and increasing page size with factor of # planes.
(See [here](https://github.com/SimpleSSD/SimpleSSD/blob/2.0/pal/old/PAL2.cc#L42), actually I does not increased page size because PAL does not support page larger than 16KB)
As shown in [this code](https://github.com/SimpleSSD/SimpleSSD/blob/2.0/pal/pal_old.cc#L484), I multiplied # of writes performed with `params.pageSize`, which has original page size (before multiplied with # planes).

P.S., If you perform research related to multi-plane operation, I STRONGLY recommend you to implement multi-plane operation in PAL. As my method always uses multi-plane operation (which writes two or more pages), it will read or program too much of data from/to NAND flash.

Thanks.
